import { AcUnit, Balcony, BeachAccess, Cable, CarCrashRounded, Coffee, FoodBank, KingBed, Kitchen, LocalBar, Lock, Phone, Pool, Restaurant, SmokeFree, SportsGymnastics, Tv, Usb, Wifi } from "@mui/icons-material";

export const DummyHotelsArr = [
  {
    id: 1,
    name: "Burj Royal",
    imageUrl: "/hotels/brujroyal.jpg",
    rating: 3.4,
    price: "AED 110",
    roomSize: "50sqm",
    bed: "1 King Bed",
    maxOccupancy: "2 Adults",
    reviews: 80,
  },
  {
    id: 2,
    name: "Noura Tower",
    imageUrl: "/hotels/nouar.jpg",
    rating: 4.0,
    price: "AED 85",
    roomSize: "40sqm",
    bed: "2 Single Beds",
    maxOccupancy: "4 Adults",
    reviews: 100,
  },
  {
    id: 3,
    name: "Binghatti Corner",
    imageUrl: "/hotels/binghatti.jpg",
    rating: 4.8,
    price: "AED 130",
    roomSize: "30sqm",
    bed: "1 Single Bed",
    maxOccupancy: "1 Adult",
    reviews: 80,
  },
  {
    id: 4,
    name: "17 Icon Bay ",
    imageUrl: "/hotels/iconbay.jpg",
    rating: 3.8,
    price: "AED 130",
    roomSize: "30sqm",
    bed: "1 Single Bed",
    maxOccupancy: "1 Adult",
    reviews: 120,
  },
  {
    id: 5,
    name: "Binghatti Lavender",
    imageUrl: "/hotels/binghattil.jpg",
    rating: 2.9,
    price: "AED 200",
    roomSize: "70sqm",
    bed: "1 King Bed",
    maxOccupancy: "3 Adults",
    reviews: 50,
  }

];

export const DummyServicesArr = [
  {
    id: 1,
    name: "Spa &Wellness",
    desc: "Up to 20% off food and services",
    image: "/services/service-1.webp",
  },
  {
    id: 2,
    name: "Restaurant",
    desc: "Children eat free, exciting fun activities.",
    image: "/services/service-2.webp",
  },
  {
    id: 3,
    name: "Fitness Center",
    desc: "Discount room rates, reward points",
    image: "/services/service-3.webp",
  },
];

export const FilterDummyHotelsArr = [
  {
    id: 1,
    name: "Deluxe King Room with Balcony",
    imageUrl: "/hotels/room1.webp",
    rating: 3.4,
    price: "AED 110",
    roomSize: "50sqm",
    bed: "1 King Bed",
    maxOccupancy: "2 Adults",
    reviews: 80,
  },
  {
    id: 2,
    name: "American Parks Trail End",
    imageUrl: "/hotels/room2.webp",
    rating: 4.0,
    price: "AED 85",
    roomSize: "40sqm",
    bed: "2 Single Beds",
    maxOccupancy: "4 Adults",
    reviews: 100,
  },
  {
    id: 3,
    name: "Hotel Deluxe Room w King Bed",
    imageUrl: "/hotels/room3.webp",
    rating: 4.8,
    price: "AED 130",
    roomSize: "30sqm",
    bed: "1 Single Bed",
    maxOccupancy: "1 Adult",
    reviews: 80,
  },
  {
    id: 4,
    name: "Tower Deluxe Room w King Bed",
    imageUrl: "/hotels/room4.webp",
    rating: 3.8,
    price: "AED 130",
    roomSize: "30sqm",
    bed: "1 Single Bed",
    maxOccupancy: "1 Adult",
    reviews: 120,
  },
  {
    id: 5,
    name: "Lodge Suite with King Bed",
    imageUrl: "/hotels/room5.webp",
    rating: 2.9,
    price: "AED 200",
    roomSize: "70sqm",
    bed: "1 King Bed",
    maxOccupancy: "3 Adults",
    reviews: 50,
  },
  {
    id: 6,
    name: "Executive Suite with Ocean View",
    imageUrl: "/hotels/room1.webp",
    rating: 4.5,
    price: "AED 250",
    roomSize: "100sqm",
    bed: "1 King Bed",
    maxOccupancy: "3 Adults",
    reviews: 200,
  },
  {
    id: 7,
    name: "Standard Double Room",
    imageUrl: "/hotels/room2.webp",
    rating: 3.0,
    price: "AED 90",
    roomSize: "35sqm",
    bed: "1 Double Bed",
    maxOccupancy: "2 Adults",
    reviews: 150,
  },
  {
    id: 8,
    name: "Luxury Suite with Balcony",
    imageUrl: "/hotels/room3.webp",
    rating: 4.9,
    price: "AED 400",
    roomSize: "120sqm",
    bed: "2 King Beds",
    maxOccupancy: "4 Adults",
    reviews: 230,
  },
  {
    id: 9,
    name: "Family Room with Sea View",
    imageUrl: "/hotels/room4.webp",
    rating: 3.6,
    price: "AED 180",
    roomSize: "80sqm",
    bed: "2 Double Beds",
    maxOccupancy: "4 Adults",
    reviews: 90,
  },
  {
    id: 10,
    name: "Junior Suite with Mountain View",
    imageUrl: "/hotels/room5.webp",
    rating: 4.2,
    price: "AED 210",
    roomSize: "70sqm",
    bed: "1 Queen Bed",
    maxOccupancy: "2 Adults",
    reviews: 170,
  },
  {
    id: 11,
    name: "Penthouse Suite with Private Pool",
    imageUrl: "/hotels/room1.webp",
    rating: 5.0,
    price: "AED 600",
    roomSize: "150sqm",
    bed: "1 King Bed",
    maxOccupancy: "2 Adults",
    reviews: 300,
  },
  {
    id: 12,
    name: "Single Room with City View",
    imageUrl: "/hotels/room2.webp",
    rating: 2.7,
    price: "AED 75",
    roomSize: "20sqm",
    bed: "1 Single Bed",
    maxOccupancy: "1 Adult",
    reviews: 40,
  },
  {
    id: 13,
    name: "Double Room with Garden View",
    imageUrl: "/hotels/room3.webp",
    rating: 3.3,
    price: "AED 95",
    roomSize: "45sqm",
    bed: "1 Double Bed",
    maxOccupancy: "2 Adults",
    reviews: 110,
  },
  {
    id: 14,
    name: "Luxury King Room with Balcony",
    imageUrl: "/hotels/room4.webp",
    rating: 4.6,
    price: "AED 190",
    roomSize: "55sqm",
    bed: "1 King Bed",
    maxOccupancy: "2 Adults",
    reviews: 160,
  },
  {
    id: 15,
    name: "Studio Apartment",
    imageUrl: "/hotels/room5.webp",
    rating: 3.5,
    price: "AED 120",
    roomSize: "60sqm",
    bed: "1 Queen Bed",
    maxOccupancy: "2 Adults",
    reviews: 95,
  },
  {
    id: 16,
    name: "Economy Room with Shared Bathroom",
    imageUrl: "/hotels/room1.webp",
    rating: 2.5,
    price: "AED 50",
    roomSize: "15sqm",
    bed: "1 Single Bed",
    maxOccupancy: "1 Adult",
    reviews: 30,
  },
  {
    id: 17,
    name: "Premium Suite with Spa Access",
    imageUrl: "/hotels/room2.webp",
    rating: 4.7,
    price: "AED 320",
    roomSize: "110sqm",
    bed: "2 King Beds",
    maxOccupancy: "4 Adults",
    reviews: 250,
  },
  {
    id: 18,
    name: "Double Room with Lake View",
    imageUrl: "/hotels/room3.webp",
    rating: 4.3,
    price: "AED 175",
    roomSize: "50sqm",
    bed: "1 Double Bed",
    maxOccupancy: "2 Adults",
    reviews: 140,
  },
  {
    id: 19,
    name: "Classic Room with City View",
    imageUrl: "/hotels/room4.webp",
    rating: 3.9,
    price: "AED 105",
    roomSize: "40sqm",
    bed: "1 Queen Bed",
    maxOccupancy: "2 Adults",
    reviews: 130,
  },
  {
    id: 20,
    name: "Superior Suite with Garden Access",
    imageUrl: "/hotels/room5.webp",
    rating: 4.4,
    price: "AED 280",
    roomSize: "90sqm",
    bed: "1 King Bed",
    maxOccupancy: "3 Adults",
    reviews: 220,
  },
];




export const facilities = [
  { label: "High-speed Wifi", icon: <Wifi /> },
  { label: "Outdoor swimming pool", icon: <Pool /> },
  { label: "Non-smoking room", icon: <SmokeFree /> },
  { label: "Fitness center", icon: <SportsGymnastics /> },
  { label: "On-site parking", icon: <CarCrashRounded /> },
  { label: "Housekeeping service", icon: <Coffee /> },
  { label: "Superb Breakfast", icon: <FoodBank /> },
  { label: "Restaurant", icon: <Restaurant /> },
];

export const roomfacilities = [
  { label: "Beachfront", icon: <BeachAccess /> },
  { label: "Balcony", icon: <Balcony /> },
  { label: "Air Conditioner", icon: <AcUnit /> },
  { label: "King Bedroom", icon: <KingBed /> },
  { label: "Safe Box", icon: <Lock /> },
  { label: "Minibar", icon: <LocalBar /> },
  { label: '40" Flat Screen HD TV', icon: <Tv /> },
  { label: "Phones", icon: <Phone /> },
  { label: "Cable/satellite", icon: <Cable /> },
  {
    label: "In-room Refrigerator",
    icon: <Kitchen />,
  },
  {
    label: "USB Outlets",
    icon: <Usb />,
  },
  {
    label: "Complimentary",
    icon: (
      <img
        src="https://sailing.thimpress.com/demo-11/wp-content/uploads/sites/25/2024/04/Complimentary.svg"
        alt="Complimentary"
        style={{ width: "24px", height: "24px" }}
      />
    ),
  },
];

export const tableplans = [
  {
    title: "Regular Plan",
    dates: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    price: [308, 308, 308, 308, 308, 308, 319],
  },
  {
    title: "July 1, 2023 to July 31, 2023",
    dates: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    price: [80, 80, 80, 80, 80, 80, 90],
  },
  {
    title: "June 7, 2023 to June 30, 2023",
    dates: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    price: [85, 85, 85, 85, 85, 85, 89],
  },
];

export const faqs = [
  {
    question:
      "Will I be able to update my subscription details another time?",
    answer: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
  },
  {
    question: "What types of photos should I upload?",
    answer: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
  },
  {
    question: "What do I get with the commission I pay?",
    answer: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
  },
];